### ISSUE TITLE
System menu versions

### ISSUE THREAD

**Issue by MethodOrMadness** [giantpune/mailboxbomb#5]
is there a known list of supported system menu versions? from experience, i know 4.3u and 3.4e work, but i browsed the github and couldnt find a list, TIA

**Comment by giantpune** [comment]
Here's the table of addresses and whatnot for each system menu version it supports.  The system menu version string can be seen out to the side in a comment.
https://github.com/giantpune/mailboxbomb/blob/master/source/main.cpp#L528

**Comment by MethodOrMadness** [comment]
yep i just logged in to check and saw it in the readme. im just stupid i guess baha
